---
- name: Install apt tools
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: present
  become: true

- name: Add Docker apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: true
  
- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present
  become: true

- name: Install docker-ce
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
    update_cache: yes
  become: true
    
- name: Add ssh user to docker group
  user:
    name: "{{ansible_env.LOGNAME}}"
    append: true
    state: present
    groups: docker
  become: true

- name: Add jenkins user to docker group
  user:
    name: "jenkins"
    append: true
    state: present
    groups: docker
  become: true

- name: Restart Jenkins service
  systemd:
    name: jenkins
    state: restarted
  become: true
